spring:
  profiles:
    active: dev
  application:
    name: device-service

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC



server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false



logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"